AWSTemplateFormatVersion: '2010-09-09'
Description: ECS service

Resource:
  TaskDefenition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Properties:
        Family: apis
        Cpu: 256
        Memory: 512
        NetworkMode: awsvpc
        RequiresCompatibilities:
          - FARGATE
        ExecutionRoleArn: !ImportValue ECSTaskExecutionRole
        ContainerDefinitions:
          - Name: cloudformation-container
            Image: 932279645368.dkr.ecr.eu-west-3.amazonaws.com/cloudformation-repo:latest
            Cpu: 256
            Memory: 512
            PortMappings:
              - ContainerPort: 8080
                Protocol: tcp


  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      ServiceName: cloudformation-service
      TaskDefinition: !Ref TaskDefenition
      Cluster: !ImportValue 'ECSCluster'
      LaunchType: FARGATE
      DesiredCount: 2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue PublicSubnet1
            - !ImportValue PublicSubnet2
          SecurityGroups:
            - !ImportValue ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: cloudformation-container
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroup

