AWSTemplateFormatVersion: '2010-09-09'
Description: ECS service

Resources:

  TaskDefenition:
    Type: AWS::ECS::TaskDefinition

    Properties:
      Family: apis
      Cpu: 512
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSTaskExecutionRole
      ContainerDefinitions:
        - Name: back-end
          Image: 932279645368.dkr.ecr.eu-west-2.amazonaws.com/back-end
          Cpu: 256
          Memory: 512
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 'apis'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'cloudformation-app-api'

  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      ServiceName: cloudformation-service-back-end
      TaskDefinition: !Ref TaskDefenition
      Cluster: !ImportValue 'ECSCluster'
      LaunchType: FARGATE
      DesiredCount: 2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue PublicSubnet1
            - !ImportValue PublicSubnet2
          SecurityGroups:
            - !ImportValue ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: front-end
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup
#        - ContainerName: back-end
#          ContainerPort: 8080
#          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: demo-tg
      VpcId: !ImportValue VPC
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /api/v1/auth
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 10
      TargetType: ip

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue Listener
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - /api/v1/auth
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward


Outputs:
  ApiEndpoint1:
    Description: Welcome API Endpoint
    Value: !Join [ '', [ 'http://', !ImportValue DomainName, '/api/v1/auth' ] ]
    Export:
      Name: 'ApiEndpoint1'

  ApiEndpoint2:
    Description: Health API Endpoint
    Value: !Join [ '', [ 'http://', !ImportValue DomainName, '/api/v1/auth' ] ]
    Export:
      Name: 'ApiEndpoint2'